/**
 * Generated by @proofkit/typegen package
 * https://proofkit.proof.sh/docs/typegen
 * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overwritten
 */
import { DataApi } from "@proofkit/fmdapi";
import { WebViewerAdapter } from "@proofkit/webviewer/adapter";
import { ZContactDetails, ZContactDetailsPortals } from "../ContactDetails";

export const client = DataApi({
  adapter: new WebViewerAdapter({ scriptName: "PK_execute_data_api" }),
  layout: "Contact Details",
  schema: { fieldData: ZContactDetails, portalData: ZContactDetailsPortals },
});
